name = "gcs"

[namespace.service.new]
required = ["credential", "project"]
optional = ["http_client_options", "pair_policy"]

[namespace.storage.new]
required = ["name"]
optional = ["work_dir"]

[namespace.storage.op.list]
optional = ["list_mode"]

[namespace.storage.op.read]
optional = ["offset", "io_callback", "size"]

[namespace.storage.op.write]
optional = ["content_md5", "content_type", "io_callback", "storage_class"]

[pairs.storage_class]
type = "string"

[pairs.project]
type = "string"

[infos.object.meta.storage-class]
type = "string"